all:
	g++ --std=c++0x -o binary-search.e binary-search.cpp
	g++ --std=c++0x -o ternary-search.e ternary-search.cpp

clean:
	rm *.e

binary:
	g++ --std=c++0x -o binary-search.e binary-search.cpp

ternary:
	g++ --std=c++0x -o ternary-search.e ternary-search.cpp